apiVersion : apps/v1
kind: Deployment
metadata:
  name: "springboottest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "springboottest"
  template:
    metadata:
      labels:
        app: "springboottest"
    spec:
      containers:
        - name: "springboottest"
          image: "testuwacrsb.azurecr.io/springboottest:1.0.1"
          ports:
          - containerPort: 80
