apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "springboottest-ingress"
    labels:
        app: "springboottest"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: test-uw-kc-sbaaaa-testuwkcsb-5c0a.07c4576f8d8c4eccb031.westus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "springboottest"
                servicePort: 80
