apiVersion: v1
kind: Service
metadata:
    name: "testuwkcsb-5c0a"
    labels:
        app: "testuwkcsb-5c0a"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testuwkcsb-5c0a"