on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        ACR_HOST: "testuwacrsb.azurecr.io"
        ACR_USER: ""
        SERVICE_NAME: "springboottest"
        TAG_NAME: "1.0.1"
        login-server: testuwacrsb.azurecr.io
        username: ${{ secrets.acr_testuwacrsb_username }}
        password: ${{ secrets.acr_testuwacrsb_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" --file  "Dockerfile" --tag ${{env.ACR_HOST}}/${{env.SERVICE_NAME}}:${{env.TAG_NAME}} --label dockerfile-path=Dockerfile
        docker push ${{env.ACR_HOST}}/${{env.SERVICE_NAME}}:${{env.TAG_NAME}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testuwkcsb_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test-uw-kc-sbaaaa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test-uw-kc-sbaaaa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test-uw-kc-sbaaaa
        container-registry-url: ${{env.ACR_HOST}}
        container-registry-username: ${{ secrets.acr_testuwacrsb_username }}
        container-registry-password: ${{ secrets.acr_testuwacrsb_password }}
        secret-name: testuwkcsbdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test-uw-kc-sbaaaa
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          ${{env.ACR_HOST}}/${{env.SERVICE_NAME}}:${{env.TAG_NAME}}
        imagepullsecrets: |
          testuwkcsbdockerauth
