name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ACR_HOST: "testuwacrsb.azurecr.io"
  ACR_USER: ""
  SERVICE_NAME: "springboottest"
  TAG_NAME: "1.0.1"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: mvn install
    - name: ACR Login
      run: az acr login --name testuwacrsb
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.ACR_HOST}}/${{env.SERVICE_NAME}}:${{env.TAG_NAME}}
     
    - name: Docker push
      run: docker push ${{env.ACR_HOST}}/${{env.SERVICE_NAME}}:${{env.TAG_NAME}}
      
      
