name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ACR_HOST: "testuwacrsb.azurecr.io"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: mvn install
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag springboottest:v1
    - name: Docker Tag
      run: docker tag mcr.microsoft.com/springboottest testuwacrsb.azurecr.io/springboottest:v1 
    - name: Docker push
      run: docker push ${{env.ACR_HOST}}/springboottest:v1
      
